language: csharp
solution: DateTimeDataAnnotations.sln
mono: none
dotnet: 2.0.0
dist: trusty
branches:
  only:
    - master
before_script:
  - dotnet restore
script:
  - dotnet build -c Release
after_script:
  - dotnet pack -c Release src/O7.DateTimeDataAnnotations.csproj
  - dotnet nuget push src/bin/Release/O7.DateTimeDataAnnotations.1.0.0.nupkg -k $NUGET_API_KEY -s https://nuget.org/